name: checksum
on:
  push:
    branches: image-burosa-devS23
jobs:
  checksum:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      # - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
      #   run: |
      #     #pip install -r requirements.txt    
      #     pip install jupyter-book matplotlib numpy pandas
      - name: Pull the most recent image
        run: |
          make pull-priv
      - name: Run the checksum diff #creates var with checksum value to be compared 
        run: |
          make checksum > checksum_runner.txt
          diff checksum_list.txt checksum_runner.txt