name: checksum
on:
  push:
    branches: image-burosa-devS23
jobs:
  checksum:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      # - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
      #   run: |
      #     #pip install -r requirements.txt    
      #     pip install jupyter-book matplotlib numpy pandas
      - name: Pull the most recent image
        run: |
          make pull-priv
      - name: Run the checksum #creates var with checksum value to be compared 
        run: |
          echo "VERIFYING IMAGE CHECKSUM"
          PERMISSIONS_CHECKSUM=$( make checksum )
          QUICK_TRIM=${PERMISSIONS_CHECKSUM::64} #quick_trim is used to get rid of the tailing "-" after the checksum
          echo "displaying modified checksum: $QUICK_TRIM "
          echo "COMPARING PULLED IMAGE CHECKSUM WITH CORRECT IMAGE CHECKSUM"
          #*********************************************
          #need to insert correct image CHECKSUM val to compare
          #*********************************************
          CHECKSUM=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
          if [[ "$QUICK_TRIM == $CHECKSUM" ]]; then
                echo "VERIFICATION COMPLETE"
                echo "SUCCESS" 
          else 
                echo "VERIFICATION COMPLETE"
                echo "FAILURE"
                exit 1
          fi
      - name: Checksum for test
        run: |
          make shatest