name: image production
on:
  push:
    branches: image-burosa-devS23
jobs:
  build:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the image
        run: |
          make build
        
      - name: Push beta version
        env:
            QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
            QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
          make push
      
  
  test:
    runs-on: ubuntu-latest #use the latest ubuntu container image
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Pull beta-version
        run: |
          make pull-priv

      - name: Show debug info
        run: |
          IMAGE_TAG=$( make show-tag )
          echo "For debugging purposes, here is the image tag:"
          echo "  $IMAGE_TAG"

      - name: Comparing checksum value
        run: |
          PERMISSIONS_CHECKSUM=$( make checksum )
          QUICK_TRIM=${PERMISSIONS_CHECKSUM::64}
          CHECKSUM=$( cat base/checksum.txt )
          if [[ "$QUICK_TRIM == $CHECKSUM" ]]; then
                echo "SUCCESS" 
          else 
                echo "FAILURE"
                echo "Here is the image checksum:"
                echo "  $QUICK_TRIM"
                echo "Here is the correct checksum:"
                echo "  $CHECKSUM"
                exit 1
          fi

      - name: Run course-specific tests
        run: |
          make -C tests test
    
  publish:
    runs-on: ubuntu-latest #use the latest ubuntu container image
    needs: test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login in to Quay.io
        env:
            QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
            QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD

      - name: Pull the beta version
        run: |
          make pull-priv

      - name: Publish to stable version
        run: |
          make publish-stable